### ISSUE TITLE
Question: [Doubts about JSON library]

### ISSUE THREAD

**Issue by hachete96** [fbarresi/fbarresi#3]
Hi Fede! I downloaded your read/write JSON library but I am not super familiar with JSON files... I implemented your sample but I am not sure if works, I really need to implemented that in my code so I will appreciated if you give me some advice about that. This is my sample code:

JSONConfig(
		Execute := FALSE , 
		File := 'C:\iot\config.json', 
		ParseMethod := 'Read' ,
		Content := 'stConfigPLC',
		HasError=> , 
		ErrorId=>);

Always returns 0 in the stConfigPLC values... I declared stConfigPLC as a global variable. Thank you very much : )

**Comment by fbarresi** [comment]
Hi!
I need more information about the json file and the structure you made for `stConfigPLC` in order to help you.
Would you post an example here?

**Comment by hachete96** [comment]
Thanks for taking the time : ) For sure, this is my code :

## Struct

```
TYPE ST_ConfigPLC :
STRUCT
	  {attribute 'Unit' := 'm/s'}
	  {attribute 'DisplayName' := 'Speed'}
	  Sensor1   : REAL ;
	  {attribute 'Unit' := 'V'}
	  {attribute 'DisplayName' := 'Voltage'}
	  Sensor2	: DINT  ;
	  {attribute 'Unit' := 'A'}
	  {attribute 'DisplayName' := 'Current'}
	  Sensor3	: DINT ;
END_STRUCT
END_TYPE
```

## JSON file

```
{
  "Values": {
    "Sensor1": 100.0,
    "Sensor2": 50,
    "Sensor3": 10
  },
  "MetaData": {
    "Sensor1": {
      "Unit": "m/s",
      "DisplayName": "Speed"
    },
    "Sensor2": {
      "Unit": "V",
      "DisplayName": "Voltage"
    },
    "Sensor3": {
      "Unit": "A",
      "DisplayName": "Current"
    }
  }
}
```

**Comment by fbarresi** [comment]
Hi, 
I need a bit more time for that reply.
The main problem here is that your plc type doesn't have the same structure of your json file.
Then you also need to specify the 'json' attribute in the plc.

I'm going to wite an example with your data for you.

Stay tuned and thank your for your patience.

**Comment by fbarresi** [comment]
Dear hachete96 , 

Please follow this tutorial.

I assume you already prepared your PC or PLC in the right way by doing the following things:

- Install TFU0003 in your target
- Reference the BeckhoffJsonReadWriter library in your twincat project

After thar you can start using the BeckhoffJsonReadWriter.

### 1. Let's start

We just start with a leer project and a `MAIN` program:

```
PROGRAM MAIN
VAR
	parser : JsonParser;
    trigger: BOOL;
END_VAR
```
```
parser(
	Execute:=trigger , 
	File:= 'C:\temp\iot.json', 
	ParseMethod:= 'Read' , // or 'Write'
	Content:= 'GVL.Variable',
	HasError=> , 
	ErrorId=> );
```

a global variable list named `GLV`:

```
VAR_GLOBAL
	Variable : JsonDUT;
END_VAR
```

and a (still leer, sMessage is just a placeholder) type named `JsonDUT`:

```
TYPE JsonDUT :
STRUCT
	{attribute 'json' := 'message'}
	sMessage : STRING;
END_STRUCT
END_TYPE
```


### 2. Model your json target

Since BeckhoffJsonReadWriter parse json file using the power of [TwinCAT.JsonExtension](https://github.com/fbarresi/TwinCAT.JsonExtension) we now have to model the structure we expect in the json file into our JsonDUT using the 'json' attribute.

In our case the json is:

```
{
  "Values": {
    "Sensor1": 100.0,
    "Sensor2": 50,
    "Sensor3": 10
  },
  "MetaData": {
    "Sensor1": {
      "Unit": "m/s",
      "DisplayName": "Speed"
    },
    "Sensor2": {
      "Unit": "V",
      "DisplayName": "Voltage"
    },
    "Sensor3": {
      "Unit": "A",
      "DisplayName": "Current"
    }
  }
}
```

So our `JsonDUT` becomes:

```
TYPE JsonDUT :
STRUCT
	{attribute 'json' := 'Values'}
	Values : SensorValues;
        {attribute 'json' := 'Metadata'}
	Infos : MetadataList;
END_STRUCT
END_TYPE
```

based on following child types:

`SensorValues`:

```
TYPE SensorValues :
STRUCT
	{attribute 'json' := 'Sensor1'}
	Sensor1 : REAL;
        {attribute 'json' := 'Sensor2'}
	Sensor2 : REAL;
        {attribute 'json' := 'Sensor3'}
	Sensor3 : REAL;
END_STRUCT
END_TYPE
```

`MetadataList`:
```
TYPE MetadataList :
STRUCT
	{attribute 'json' := 'Sensor1'}
	Sensor1 : SensorMetadata;
        {attribute 'json' := 'Sensor2'}
	Sensor2 : SensorMetadata;
        {attribute 'json' := 'Sensor3'}
	Sensor3 : SensorMetadata;
END_STRUCT
END_TYPE
```

`SensorMetadata`
```
TYPE MetadataList :
STRUCT
	{attribute 'json' := 'Unit'}
	Unit : STRING;
        {attribute 'json' := 'DisplayName'}
	DisplayName : STRING;
END_STRUCT
END_TYPE
```

### 3. Let it run!

You can now activate the configuration and change to run mode.
Set the variable `MAIN.trigger` in order to read your file and parse it `GVL.Variable`.

**Comment by fbarresi** [comment]
closed due to inactivity
